services:
  browser:
    image: seleniarm/standalone-firefox:114.0
    shm_size: 2g
    environment:
      START_XVFB: false
    healthcheck:
      test: ["CMD", "curl", "--fail", "-s", "-o", "/dev/null", "http://localhost:4444"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "4444:4444"
      - "7900:7900"

  db:
    image: influxdb:2.7-alpine
    restart: unless-stopped
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: speedtest
      DOCKER_INFLUXDB_INIT_PASSWORD: speedtest
      DOCKER_INFLUXDB_INIT_ORG: speedtest
      DOCKER_INFLUXDB_INIT_BUCKET: speedtest
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: speedtest-admin-token
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb2

  app:
    build: .
    profiles:
      - app
    depends_on:
      - browser
      - db
    environment:
      BROWSER_URL: http://browser:4444
      DB_URL: http://db:8086
      DB_AUTH_TOKEN: speedtest-admin-token
      DB_ORG: speedtest
      DB_BUCKET: speedtest
    volumes:
      - .:/app

volumes:
  influxdb: